# Generated by Django 5.1 on 2024-09-18 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receiver_fullname", models.CharField(max_length=100, null=True)),
                ("receiver_email", models.EmailField(max_length=50, null=True)),
                ("receiver_phone", models.CharField(max_length=12, null=True)),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("city", models.CharField(max_length=50, null=True)),
                ("address", models.CharField(max_length=200, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Order: full details",
                "verbose_name_plural": "Orders full details",
            },
        ),
    ]
