# Generated by Django 5.1 on 2024-09-18 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_orderstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="orders.orderstatus",
            ),
        ),
    ]
