# Generated by Django 5.1 on 2024-09-19 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_order_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="user",
            new_name="created_by",
        ),
    ]
