# Generated by Django 5.1 on 2024-09-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_rename_user_order_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverytype",
            name="free_delivery_order_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="deliverytype",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="products_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="total_cost",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
