# Generated by Django 5.1 on 2024-09-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_order_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_comment",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
