# Generated by Django 5.1 on 2024-10-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_order_payment_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliverytype",
            options={
                "verbose_name": "Order: delivery type",
                "verbose_name_plural": "Orders: delivery types",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "verbose_name": "Order: full details",
                "verbose_name_plural": "Orders: full details",
            },
        ),
        migrations.AlterModelOptions(
            name="orderstatus",
            options={
                "verbose_name": "Order: status",
                "verbose_name_plural": "Orders: statuses",
            },
        ),
        migrations.AlterModelOptions(
            name="paymenttype",
            options={
                "verbose_name": "Order: payment type",
                "verbose_name_plural": "Orders: payment types",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="products_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10
            ),
        ),
    ]
