# Generated by Django 5.1 on 2024-10-07 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0003_alter_profile_unique_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avatar",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avatar",
                to="user_profile.profile",
            ),
        ),
    ]
