# Generated by Django 5.1 on 2024-09-14 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, unique=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("count", models.PositiveIntegerField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("free_delivery", models.BooleanField(default=False)),
                (
                    "shot_description",
                    models.CharField(default="Not prescribed", max_length=1000),
                ),
                (
                    "full_description",
                    models.CharField(default="See short description", max_length=1000),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=2, null=True
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "sorting_index",
                    models.PositiveSmallIntegerField(
                        blank=True, db_index=True, default=0, null=True
                    ),
                ),
                ("is_limited", models.BooleanField(db_index=True, default=False)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product: full details",
                "verbose_name_plural": "Products: full details",
            },
        ),
    ]
