# Generated by Django 5.1 on 2024-09-14 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("text", models.TextField(max_length=1000)),
                ("rate", models.SmallIntegerField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product: review",
                "verbose_name_plural": "Products: reviews",
                "unique_together": {("email", "product")},
            },
        ),
    ]
