# Generated by Django 5.1 on 2024-09-14 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_productreview"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAndSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("value", models.CharField(max_length=150)),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="specifications",
                        through="products.ProductAndSpecification",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product: image",
                "verbose_name_plural": "Products: specifications",
            },
        ),
        migrations.AddField(
            model_name="productandspecification",
            name="specification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productspecification",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productandspecification",
            unique_together={("product", "specification")},
        ),
    ]
