# Generated by Django 5.1 on 2024-09-14 17:06

import django.db.models.deletion
import products.models.product_image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_productandspecification_productspecification_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "src",
                    models.ImageField(
                        max_length=150,
                        upload_to=products.models.product_image.get_product_image_saving_path,
                    ),
                ),
                (
                    "alt",
                    models.CharField(
                        default="Image is currently unavailable!", max_length=150
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product: image",
                "verbose_name_plural": "Products: images",
            },
        ),
    ]
