# Generated by Django 5.1 on 2024-09-14 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_productimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAndTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="tags",
                        through="products.ProductAndTag",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product: tag",
                "verbose_name_plural": "Products: tags",
            },
        ),
        migrations.AddField(
            model_name="productandtag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.producttag"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productandtag",
            unique_together={("product", "tag")},
        ),
    ]
