# Generated by Django 5.1 on 2024-09-18 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_productandtag_producttag_productandtag_tag_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productspecification",
            options={
                "verbose_name": "Product: specification",
                "verbose_name_plural": "Products: specifications",
            },
        ),
    ]
