# Generated by Django 5.1 on 2024-09-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_productspecification_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="received_amount",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
