# Generated by Django 5.1 on 2024-09-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_product_received_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="received_amount",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
