# Generated by Django 5.1 on 2024-09-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_alter_product_received_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_sale",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
