# Generated by Django 5.1 on 2024-09-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_product_is_sale"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="is_sale",
            new_name="is_sales",
        ),
        migrations.AddField(
            model_name="product",
            name="sales_from",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="sales_price",
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="sales_to",
            field=models.DateField(null=True),
        ),
    ]
